# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crewing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crewing

  target 'CrewingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CrewingUITests' do
    # Pods for testing
  end

  pod 'IQKeyboardManagerSwift'

  pod 'Charts'
  
  pod 'KakaoSDK'
  
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwift'
  
  pod 'naveridlogin-sdk-ios'
  
  pod 'Moya'
  
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'Firebase/Messaging'

  
  
end
