version: '3.8'

services:
    backend:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: jobqa-backend
        ports:
            - "8000:5000"
        volumes:
            - ../backend:/app
        environment:
            - FLASK_APP=__init__.py
            - FLASK_ENV=development
            - DB_HOST=db
            - DB_USER=testuser
            - DB_PASSWORD=testpass
            - DB_NAME=testdb
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: jobqa-db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=testdb
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=testpass
        volumes:
            - ../db:/docker-entrypoint-initdb.d