version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: jobqa-backend
    ports:
      - "8000:5000"
    volumes:
      - ../app:/app/app
      - ../manage.py:/app/manage.py
      - ../requirements.txt:/app/requirements.txt
    environment:
      - COMPOSE_PROJECT_NAME=JobQA-Dev
      - APP_ENV=development
    env_file:
      - ../config/.env.backend
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py run --host=0.0.0.0

  db:
    image: mysql:8.0
    container_name: jobqa-db
    ports:
      - "3306:3306"
    env_file:
      - ../config/.env.db
    volumes:
      - ../db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
